CREATE DATABASE jacket;
CREATE DATABASE jacket_api;

GRANT ALL PRIVILEGES ON jacket_api.* TO 'jacket'@'localhost' \
  IDENTIFIED BY 'JACKET_PASS';
GRANT ALL PRIVILEGES ON jacket_api.* TO 'jacket'@'%' \
  IDENTIFIED BY 'JACKET_PASS';
GRANT ALL PRIVILEGES ON jacket.* TO 'jacket'@'localhost' \
  IDENTIFIED BY 'JACKET_PASS';
GRANT ALL PRIVILEGES ON jacket.* TO 'jacket'@'%' \
  IDENTIFIED BY 'JACKET_PASS';

